version: "3.8"
services:
  db:
    container_name: postgres_db_container
    hostname: postgres_db
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - 5432:5432

  python:
    container_name: python_OS
    hostname: python_os
    build: ./python/
    ports:
      - 8001:8001
    volumes:
      - ./.dbt/:/root/./dbt/
    depends_on:
      - db
    links:
      - "db:database"
  
  
  superset:
    container_name: superset
    build:
      context: ./superset
      dockerfile: Dockerfile
       ports:
      - 8083:8000
      depneds_on:
         - db
      
